### PR TITLE
Add support for pod diffs.

### PR DESCRIPTION
**Pull request by asherf**

### CODE REVIEW

**Comment by joe-elliott** [comment]
I thought pods were immutable? I could be wrong, it's been awhile since I was deep in k8s land.

**Comment by asherf** [comment]
For annotating grafana charts purposes, this will be useful because it can log pods being replaced (create/deleted), this can be triggered by pod getting killed by k8s (oom killer or getting evicted for other reasons) or a pod getting replaced due to a node dying.
Another use case this allows is detect and logging (and thus annotating) container restarts with pods (which is the use case we are interested in)

**Comment by joe-elliott** [comment]
I believe everything you mentioned are kubernetes events and we use this project:

https://github.com/heptiolabs/eventrouter

to dump those to stdout.

**Comment by aantn** [comment]
If someone is still looking for a solution, I wrote an open source project writes Grafana annotations when Kubernetes objects change. It supports pod creation/update/deletion and you can specify in YAML which fields to monitor.

https://docs.robusta.dev/master/catalog/actions/grafana.html

**Pull request closed without merging**
