### PR TITLE
Fix Service Account Namespace

### PR DESCRIPTION
**Pull request by weiwu-sre**

### CODE REVIEW

**Comment by joe-elliott** [comment]
I was purposefully trying not to bind this to a specific namespace, but now that I'm reviewing the yaml I see that the cluster role binding requires a namespace for the service account binding.

Should we just explicitly put everything in default?

**Comment by weiwu-sre** [comment]
> I was purposefully trying not to bind this to a specific namespace, but now that I'm reviewing the yaml I see that the cluster role binding requires a namespace for the service account binding.
> 
> Should we just explicitly put everything in default?

Deployment and service account need to be on same namespace. Also clusterrolebinding requires a namespace.

Either `default` or `kube-system` should be fine in my opinion.

**Comment by joe-elliott** [comment]
I like `default`.  Do you mind adding namespace to all objects? If not I can get it done.

**Comment by weiwu-sre** [comment]
> I like `default`. Do you mind adding namespace to all objects? If not I can get it done.

I think this is the only place missing namespace. `clusterrole` and `clusterrolebinding` are cluster level resources, don't require namespace.

**Comment by joe-elliott** [comment]
Oh yeah, you're right.  For some reason I thought deployment and other resources were lacking namespace too.

Merging.  Thanks for the contribution!

**Pull request merged**
